/// <reference path="C:\Users\z3504028\Source\Repos\WorldNomads-Test\NumericSequenceCalculator_Web_Interface\Scripts/jquery-1.10.2.js" />
/// <reference path="C:\Users\z3504028\Source\Repos\WorldNomads-Test\NumericSequenceCalculator_Web_Interface\Scripts/Default/component.js" />
/// <reference path="C:\Users\z3504028\Source\Repos\WorldNomads-Test\NumericSequenceCalculator_Web_Interface\Scripts/Default/series.js" />
/// <reference path="C:\Users\z3504028\Source\Repos\WorldNomads-Test\NumericSequenceCalculator_Web_Interface\Scripts/Default/Default.js" />

///Test Generated series
describe("generateFibonacciSeries Function test", function () {
    //variable initilization
    var endvariable1 = 145;
    var testFiboList1 = [0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 145];
    var testFiboList2 = [0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 145];
    var testresult = null;
    var testresult2 = null;

    var series = new SR.Series();
    // Test setup 
    beforeEach(function () {
        testresult = series.generateFibonacciSeries(endvariable1);
        testresult2 = series.generateFibonacciSeries(endvariable1);
    });

    // actual test
    it("Test Result generated by Fibonacci function should be equals to testFiboList1", function () {
        expect(String(testresult)).toBe(String(testFiboList1));
    });
    it("Test Result generated by Fibonacci function should not be equals to testFiboList2", function () {
        expect(String(testresult2)).not.toBe(String(testFiboList2));
    });
})